name: isolated_http_client
description: http clint with requests cancelation and isolate decoding in separated isolate
version: 1.4.2
homepage: https://github.com/Renesanse/isolated_http_client

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  meta: ^1.4.0
  http_parser: ^4.0.0
  worker_manager: ^4.0.2
